### ISSUE TITLE
A small bug when importing dataset and questions

### ISSUE THREAD

**Issue by bamps53** [xuyuan/waymo_2d_tracking#1]
Thanks for sharing simple but very strong solution for 2d tracking!
I just want to let you know I found small bug.

I think below line should be fixed to correctly import dataset.
https://github.com/xuyuan/waymo_2d_tracking/blob/1e2d1c36d06aa45c236e07ddad3801df9ef3b6a6/data/__init__.py#L3

This change worked for me.
```from detnet.data.coco import COCODetection```

And I have several questions.
1. Do you have any plan to release trained model weight? I'd like to see how your model works but training on waymo dataset takes forever...
2. In your argparse, there is a configuration which specifies amp or apex_opt_level. I tried both but failed, even if I update pytorch to 1.6.0. Did you make sure this can be used for this 2d tracking model? Or is this just there so that you can use for other project?
3. For tracking, have you compared other method, such as [deep sort](https://github.com/nwojke/deep_sort)? I don't actually expect this affect score much, but just want to know SORT was the best among the method or you just use it.

Thanks,

**Comment by xuyuan** [comment]
> Thanks for sharing simple but very strong solution for 2d tracking!
> I just want to let you know I found small bug.

Thanks for reporting, just fixed in 816788a 


>     1. Do you have any plan to release trained model weight? I'd like to see how your model works but training on waymo dataset takes forever...

we cannot publish trained models according to waymo.
check "Why can’t I publish my trained model?" in https://waymo.com/open/faq/

>     2. In your argparse, there is a configuration which specifies amp or apex_opt_level. I tried both but failed, even if I update pytorch to 1.6.0. Did you make sure this can be used for this 2d tracking model? Or is this just there so that you can use for other project?

unfortunately `detectron2` models don't work with `amp`

>     3. For tracking, have you compared other method, such as [deep sort](https://github.com/nwojke/deep_sort)? I don't actually expect this affect score much, but just want to know SORT was the best among the method or you just use it.

we have  only tried SORT.

**Comment by bamps53** [comment]
Thanks for quick answer, now I understand.
I'll try to train by myself.

**Comment by tugstugi** [comment]
> 3\. For tracking, have you compared other method, such as [deep sort](https://github.com/nwojke/deep_sort)? I don't actually expect this affect score much, but just want to know SORT was the best among the method or you just use it.

For comparison, we have also tried V-IOU, but couldn't successfully tune the parameter. Anyway V-IOU was not allowed for the competition because it is not an online algorithm.
