### ISSUE TITLE
Can't run ResNeSt200

### ISSUE THREAD

**Issue by bamps53** [xuyuan/waymo_2d_tracking#2]
I noticed you have `faster_cascade_rcnn_ResNeSt_200_FPN_syncbn_range-scale_1x.yaml` in coco-detection config folder so I want to compare the performance with ResNeXt152.
I tried to run but failed, because there is no resnest implementation in detectron2 library.
Next I tried to change detectron2 library to [forked one](https://github.com/zhanghang1989/detectron2-ResNeSt), but then I realized some strange behaviors such as couldn't evaluate at all. I assume it's due to detectron2 version difference, but I couldn't find what exactly it is.

my question is:
1. Have you compared with ResNeSt200 with ResNeXt152 and ResNeXt152 performed better?
2. Is there any way to run ResNeSt200 with this repo? If not, is it possible to make it works somehow?

Thanks in advance.

**Comment by xuyuan** [comment]
Yes, you need to install ResNest fork of detectron2.

I have tried evaluating pretrained ResNeSt200 model on COCO 2017, the score is close to what they claim, but I haven't  trained it on any dataset yet.
