### ISSUE TITLE
Waymo dataset

### ISSUE THREAD

**Issue by linchunmian** [xuyuan/waymo_2d_tracking#3]
Hi, author, thanks for your great job.
However, the Waymo data is too huge for me to pull in the local memory. I want to know which data should I download? 
Also, it is diffuicult for me to get the data from the official website, due to some network problem. Could you please provide the subset for me to support the model training and testing?
Any help would be appreciated a lot.

**Comment by tugstugi** [comment]
See the Waymo dataset license agreement. Only Waymo can distribute the dataset.
