### ISSUE TITLE
How can I get the accuracy for the test data?

### ISSUE THREAD

**Issue by Eric716** [xuyuan/waymo_2d_tracking#6]
Ho can I get the accuracy for the test data?
the **inference.py** ouput log doesn't has the ap, ar, T, and the metrix score just like the train.py shows 
Is there any parameters to use to get it?

I want the test rusult like this below!!! 
![螢幕擷取畫面 2022-06-11 204739](https://user-images.githubusercontent.com/48532191/173188766-7fd2b28f-2afc-46a0-9021-1c8da8de6d74.jpg)

It's very strange that I cannot find it, Thanks a lot!!!!

**Comment by tugstugi** [comment]
You have to submit the inference results into the Waymo challange website to get the test metrics.
